### ISSUE TITLE
the version of TensorFlow

### ISSUE THREAD

**Issue by asmw707** [thanhson28/icme2023#1]
What is the version of TensorFlow installed?

**Comment by asmw707** [comment]
Traceback (most recent call last):
  File "/home/smeng/icme2023/evaluate_ooc_original_cosmos.py", line 10, in <module>
    from utils.config import *
  File "/home/smeng/icme2023/utils/__init__.py", line 1, in <module>
    from .common_utils import *
  File "/home/smeng/icme2023/utils/common_utils.py", line 8, in <module>
    from utils.config import TARGET_DIR
  File "/home/smeng/icme2023/utils/config.py", line 5, in <module>
    import tensorflow_hub as hub
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow_hub/__init__.py", line 85, in <module>
    _ensure_tf_install()
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow_hub/__init__.py", line 49, in _ensure_tf_install
    import tensorflow as tf
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/smeng/anaconda3/envs/ic/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates


tensorflow                         2.6.0
tensorflow-estimator               2.15.0
tensorflow-hub                     0.12.0
python 3.9
torch 2.5.1
